[metadata]

name = AlphaPurify
version = 0.1.0
author = Elias Wu
author_email = eliaswu71@gmail.com
description = A powerful quantitative factor cleaning and analysis library
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/eliasswu/AlphaPurify

classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
requires_python = >=3.10

[options]

packages = find:

python_requires = >=3.10

install_requires =
    pandas
    polars
    duckdb
    plotly
    numpy
    scipy
    pyarrow
    joblib
    scikit-learn
    tqdm

[options.packages.find]

where = .

include = alphapurify*

exclude = tests*
          docs*

[options.extras_require]
